# Site settings   http://jekyll.bootcss.com/docs/configuration/
title: seavers的博客
email: seavers@163.com
description: > # this means to ignore newlines until "baseurl:"
  Looking for Interest
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://www.lianghaijun.com" # the base hostname & protocol for your site
#twitter_username: seavers
github_username:  seavers

permalink: /:year-:month-:day-:title.html


# Build settings
markdown: kramdown  ## maruku|rdiscount|redcarpet|kramdown
kramdown:
#   pygments: true
   input: GFM
   extensions:
     - autolink
     - footnotes
     - smart
   use_coderay: true
#  syntax_highlighter: rouge
   coderay:
     coderay_line_numbers: table 
     coderay_wrap: div
